"""Init

Revision ID: aadc2b5329f8
Revises: 
Create Date: 2022-04-17 12:08:51.121325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadc2b5329f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('mapname', sa.Text(), nullable=True),
    sa.Column('players', sa.Integer(), nullable=True),
    sa.Column('players_max', sa.Integer(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.Column('last_try', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_group_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.Text(), nullable=False),
    sa.Column('filter_value', sa.Text(), nullable=False),
    sa.Column('is_black_list', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_group_association',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_group_id'], ['server_group.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('server_id', 'server_group_id')
    )
    op.create_table('server_group_filter_association',
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['server_group_filter.id'], ),
    sa.ForeignKeyConstraint(['server_group_id'], ['server_group.id'], ),
    sa.PrimaryKeyConstraint('filter_id', 'server_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_group_filter_association')
    op.drop_table('server_group_association')
    op.drop_table('server_group_filter')
    op.drop_table('server_group')
    op.drop_table('server')
    # ### end Alembic commands ###
